---
title: "Gibbs Sampling Algorithm"
author: ""
date: "5/4/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(MCMCpack)
# install package "psych"
```

```{r importing data}
hurr_df <- read_csv("./data/hurricane703.csv") %>%
  drop_na() %>% 
  group_by(ID) %>% 
  filter(n() > 1) %>% 
  # create delta variables and wind lag - wind speed at time t, Y(t)
  mutate(lat_change = c(0, diff(Latitude, lag = 1)), # I put zero for first entry, could be NA
         lng_change = c(0, diff(Longitude, lag = 1)),
         wind_change = c(0, diff(Wind.kt, lag = 1)),
         wind_lag = lag(Wind.kt, n = 1)) %>% 
  dplyr::select(ID, wind_lag, lat_change, lng_change, wind_change, Wind.kt) %>% 
  nest(y = Wind.kt, x = wind_lag:wind_change) %>%  
  mutate(x = map(.x = x, .f = ~model.matrix(~., data = .x)),
         y = map(.x = y, .f = pull))

hurr_list <- list(
  y = hurr_df$y,
  x = hurr_df$x
)


# you can extract data like this
hurr_list$x[[1]]
hurr_list$y[[1]]

# list of theta parameters
theta <- list(
  "beta" = list("beta" = matrix(data = 0, nrow = 1, ncol = 5),
                "mu" = 0,
                "sigma" = 0),
  "B" = list(matrix(data = 0, nrow = nrow(hurr_df), ncol = 5),
             "mu" = 0,
             "sigma" = 0),
  "sigma2" = c(1),
  "sigma_m" = matrix(data = .5, nrow = 5, ncol = 5) + diag(.5, 5, 5)
)
```

```{r log posterior distributions, eval = FALSE}
# log posterior of sigma^2
log_sigma2 <- function(data, i){
  # alpha parameter of distribution
  alpha = 1 + sum(dim(data[[i]]$y)) / 2
  # beta parameter of distribution
  b = (1/2) * sum(t(data[[i]]$y - data[[i]]$x %*% t(theta$beta)) %*% diag(length(data[[i]]$y)) %*% (data[[i]]$y - data[[i]]$x %*% t(theta$beta)))
  # pulling sigma^2 from theta list
  tau = theta$sigma2
  
  return(alpha * log(b) - log(gamma(alpha)) + (alpha - 1) * log(tau) - tau * b)
}

# log posterior of beta
log_beta <- function(){
  v = sum(theta$sigma_m)
  u = sum(theta$sigma_m %*% t(theta$beta))
  
  return(-(1/2) * log(det(2 * pi * solve(v, tol = 1e-95))) - (1/2) * t((theta$beta - solve(v, tol = 1e-95) %*% u)) %*% solve(v, tol = 1e-95) %*% (theta$beta - solve(v, tol = 1e-95) %*% u))
}

# log posterior of B
log_B <- function(data, i){
  v = t(data$x[[i]]) %*% (1 / diag(theta$sigma2)) %*% data[[i]]$x + theta$sigma_m
  u = data[[i]]$x %*% (1 / diag(theta$sigma2)) %*% data[[i]]$y + theta$sigma_m %*% t(theta$beta)
  
  return(-(1/2) * log(det(2 * pi * solve(v, tol = 1e-95))) - (1/2) * t((theta$B - solve(v, tol = 1e-95) %*% u)) %*% solve(v, tol = 1e-95) %*% (theta$B - solve(v, tol = 1e-95) %*% u))
}
```

```{r conditional distributions}
beta_dist <- function(sigma, B){
  # sigma stored as inverse
  u_matrix <- matrix(0, nrow = 5, ncol = nrow(hurr_df))
  for(i in 1:nrow(hurr_df)){
    
    u_matrix[,i] = sigma %*% t(matrix(B[i,], ncol = 5))
    
  }
  
  u = rowSums(u_matrix)

  mu = (solve(sigma, tol = 1e-95) / nrow(hurr_df)) %*% matrix(u, nrow = 5)
  sigma = psych::cor.smooth(solve(sigma, tol = 1e-95) / nrow(hurr_df))
  
  sample = mvrnorm(n = 1, mu, sigma)
  
  return(list("beta" = sample,
              "mu" = mu,
              "sigma" = sigma))
}

B_dist <- function(x, y, sigma2, sigma_m, beta){
  B_list <- list()
  
  v_list <- list()
  for(i in 1:nrow(hurr_df)){
    if(length(y[[i]]) < 2){
      next
    }
    attr(x[[i]], which = "assign") <- NULL
    attr(x[[i]], which = "dimnames") <- NULL
    y_adj <- y[[i]][-1]
    
    mat <- diag(sigma2, nrow = length(y_adj), ncol = length(y_adj))
    
    u <- t(x[[i]]) %*% solve(mat, tol = 1e-95) %*% y_adj + solve(sigma_m, tol = 1e-95) %*% t(beta)
    v <- t(x[[i]]) %*% solve(mat, tol = 1e-95) %*% x[[i]] + solve(sigma_m, tol = 1e-95)
    
    mu <- solve(v, tol = 1e-95) %*% u
    sigma <- psych::cor.smooth(solve(v, tol = 1e-95))
    v_list[[i]] <- v
    
    B_list[[i]] <- mvrnorm(n = 1, mu, sigma)
    
  }
  
  B_matrix <- do.call(rbind, B_list)
  
  return(list("B" = B_matrix,
              "mu" = mu,
              "v" = v_list))
  
}

sigma2_dist <- function(B, x, y){
  length_vec = sapply(y, length)

  beta_vec <- c()
  for(i in 1:nrow(hurr_df)){
    attr(x[[i]], which = "assign") <- NULL
    attr(x[[i]], which = "dimnames") <- NULL
    y_adj <- y[[i]][-1]
    
    #res <- t(y_adj - x[[i]] %*% B[i,]) %*% diag(length(y_adj)) %*% (y_adj - x[[i]] %*% (B[i,]))
    res <- sum((y_adj - (x[[i]] %*% B[i,]))^2)
    
    beta_vec[i] <- res
  }
  
  # alpha parameter of distribution
  alpha = sum(length_vec) / 2
  # beta parameter of distribution
  b = (1/2) * sum(beta_vec)
  
  sample = rinvgamma(n = 1, shape = alpha, scale = b)
  return(sample)
}

sigma_m_dist <- function(beta, B){
 prev_matrix <- matrix(0, nrow = 5, ncol = 5)
 
 for(i in 1:nrow(hurr_df)){
   
   matrix <- t(B[i,] - beta) %*% (B[i,] - beta) + prev_matrix
   
   prev_matrix <- matrix
 }
 matrix <- matrix + diag(1, 5, 5)
 
 #mat_param <- solve(matrix)
  
 n = nrow(hurr_df)
 
 # output is covariance matrix
 sample = matrix(riwish(v = n + 6, S = matrix),
                 ncol = 5)
  
 #sample = matrix(rWishart(n = 1, df = n + 6, Sigma = mat_param),
 #                ncol = 5)
 
  return(sample)
}
```

```{r gibbs sampling function, error = TRUE}
gibbs_fun <- function(iter, start, data){
  set.seed(052022)
  beta_list <- list()
  sigma_list <- list()
  sigma2_list <- list()
  B_list <- list()
  
  beta_list[[1]] <- start$beta
  sigma_list[[1]] <- start$sigma_m
  sigma2_list[[1]] <- start$sigma2
  B_list[[1]] <- theta$B
  # added code to catch data before error
  tryCatch(expr = {
  for (i in 2:iter){
    #browser()
    beta_list[[i]] <- beta_dist(sigma = sigma_list[[i-1]], B = B_list[[i-1]][[1]])
    sigma_list[[i]] <- sigma_m_dist(beta = matrix(beta_list[[i]][[1]], ncol = 5), B = B_list[[i-1]][[1]])
    sigma2_list[[i]] <- sigma2_dist(B = B_list[[i-1]][[1]], x = data$x, y = data$y)
    B_list[[i]] <- B_dist(x = data$x, y = data$y, sigma2 = sigma2_list[[i]],
                          sigma_m = sigma_list[[i]], beta = matrix(beta_list[[i]][[1]], ncol = 5))
  }
  },
  error = function(e){print(e)},
  finally = list(beta = beta_list, sigma_m = sigma_list,
              sigma2 = sigma2_list, B = B_list)
  )
  return(list(beta = beta_list, sigma_m = sigma_list,
              sigma2 = sigma2_list, B = B_list))
  
}
test <- gibbs_fun(iter = 1000, start = theta, data = hurr_list)
```

```{r result visualizations}
# functions to extract beta and B values from gibbs output
beta_compiler <- function(list){
  beta_res_list <- list()
  
  for (i in 1:length(list)){
    beta_res_list[[i]] <- list[[i]]$beta
  }
  
  return(beta_res_list)
}

B_compiler <- function(list){
  B_res_list <- list()
  
  for(i in 1:length(list)){
    B_res_list[[i]] <- list[[i]][[1]]
  }
  
  return(B_res_list)
}
load("./data/gibbs_res.RData")

### visualizing beta values, load in ./data/gibbs_res.RData
# beta_res_list <- beta_compiler(list = test$beta)
# beta_vec <- data.frame(do.call(rbind, beta_res_list)) %>% 
#   rename(beta0 = 1, beta1 = 2, beta2 = 3, beta3 = 4, beta4 = 5) %>% 
#   pivot_longer(cols = beta0:beta4, names_to = "beta", values_to = "estimate") %>% 
#   group_by(beta) %>% 
#   mutate(ind = c(1:length(beta_res_list)))

ggplot(data = beta_vec, aes(y = estimate, col = beta)) +
  geom_line(aes(ind))

ggplot(data = beta_vec, aes(x = estimate, fill = beta)) +
  geom_histogram(alpha = 0.5, position = "identity") +
  facet_wrap(~beta, ncol = 3)

### this code extracts estimates, just load in ./data/gibbs_res.RData
# beta_estimate <- beta_vec[2551:5000,] %>% # we want to specify the second half of runs 
#   group_by(beta) %>% 
#   summarise(avg_est = mean(estimate))
# 
# sigma2_vec <- do.call(rbind, test$sigma2)
# sigma2_est <- mean(sigma2_vec[501:1000])
# 
# sigma_est <- Reduce("+", test$sigma_m[501:1000]) / length(test$sigma_m[501:1000])
# 
# B_res_list <- B_compiler(list = test$B)
# B_est <- Reduce("+", B_res_list[501:1000]) / length(B_res_list[501:1000])
# 
# save(beta_res_list, beta_vec, beta_estimate,
#      B_res_list, B_est, sigma2_vec, sigma2_est,
#      sigma_est, file = "./data/gibbs_res.RData")

# visualizing sigma2 values
mean(sigma2_vec)
plot(x = sigma2_vec, xaxt = "n", type = "l")
acf(sigma2_vec, pl = TRUE)
```

```{r making predictions}
gibbs_predict <- function(data, B){
  y_pred_list <- list()
  for(i in 1:length(data$x)){
    y_pred_list[[i]] <- data$x[[i]] %*% t(t(B[i,]))
  }
  return(y_pred_list)
}
hurr_list$x[[1]] %*% t(t(B_est[1,]))
y_hat <- gibbs_predict(data = hurr_list, B = B_est)

mse_function <- function(actual, predicted){
  mse_list <- list()
  
  for(i in 1:length(actual)){
    mse_list[[i]] <- mean((actual[[i]][-1] - as.vector(predicted[[i]]))^2)
  }

  return(mse_list)
}

mse <- mse_function(actual = hurr_list$y, predicted = y_hat)
```

