---
title: "Question6"
author: "Jie Liu jl5788"

output: pdf_document
---
```{r echo = FALSE, message=FALSE,warning = FALSE}
library(tidyverse)
library(dplyr)
library(caret)
```

 
```{r echo = FALSE, message=FALSE,warning = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
  , warning = FALSE , message=FALSE
)

theme_set(
  theme_bw() +
    theme(
      legend.position="bottom",
      plot.title = element_text(hjust=0.5),
      plot.subtitle=element_text(hjust=0.5),
      plot.caption=element_text(hjust=0.0)
    )
)

options(ggplot2.continuous.colour="viridis",
        ggplot2.countinuous.fill="viridis")

scale_colour_discrete=scale_colour_viridis_d
scale_fill_discrete=scale_fill_viridis_d
```

```{r}
hurricaneOutcome <- read.csv("data/hurricaneoutcome2.csv") %>% janitor::clean_names() %>%  
                    mutate(damage=substr(damage,start=2,stop=10),
                           month=match(month,month.name),
                           damage=as.numeric(damage),
                           deaths=str_remove(deaths,","),
                           deaths=as.numeric(deaths),
                           nature=as.factor(nature))

hurricaneOutcome %>% distinct(hurrican_id)


rownames(hurricaneOutcome) <- hurricaneOutcome$hurrican_id

hurricane702 <- read_csv("./data/hurricane703.csv") %>% mutate(ID=tolower(ID))

hurricane43 <- subset(hurricane702,ID %in%rownames(hurricaneOutcome)) 




```

```{r}
# load data
load("./data/gibbs_res.RData")
```

```{r data preparation}
# avg of last 100 beta_i, 700*5
B_est2 <- Reduce("+", B_res_list[501:1000]) / length(B_res_list[501:1000])
colnames(B_est2) <- c('beta0', 'beta1' ,'beta2', 'beta3', 'beta4')

extra_df <- read_csv("./data/hurricane703.csv") %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  group_by(id) %>% 
  dplyr::select(id) %>% 
  filter(n() > 2) %>% 
  filter(row_number() == 1) %>% 
  mutate(id=tolower(id))

rownames(extra_df) <- extra_df$id

B_est_res <- data.frame(cbind(rownames(extra_df),B_est2)) %>% filter(V1 %in% rownames(hurricaneOutcome))


hurricane43.infor <- cbind(hurricaneOutcome,B_est_res) %>% select(-V1,-hurrican_id) %>% 
                      mutate(beta0=as.numeric(beta0),
                             beta1=as.numeric(beta1),
                             beta2=as.numeric(beta2),
                             beta3=as.numeric(beta3),
                             beta4=as.numeric(beta4)
                             )
```

## Elastic for damage without parameter information
```{r}
set.seed(1)

elastic.fit10 <- train(log(damage)~.,
                   data=hurricaneOutcome1,
                   method="glmnet",
                   tuneGrid=expand.grid(alpha=seq(0,1,length=21),
                                        lambda=exp(seq(2,-5,length=100))),
                   trControl=ctrl1)

elastic.fit10$bestTune

myCol <- rainbow(25)
myPar <- list(superpose.symbol=list(col=myCol),
              superpose.line=list(col=myCol))
plot(elastic.fit10,par.settings=myPar)



coef(elastic.fit10$finalModel,s=elastic.fit10$bestTune$lambda)

lm.damage.nopar <- lm(log(damage) ~ season + month + nature + maxspeed + meanspeed + percent_usa, data= hurricaneOutcome1)
summary(lm.damage.nopar)

```
## Elastic for damage with parameter information
```{r}
set.seed(1)
hurricane43.infor1 <- hurricane43.infor %>% select(-deaths)
elastic.fit11 <- train(log(damage)~.,
                   data=hurricane43.infor1,
                   method="glmnet",
                   tuneGrid=expand.grid(alpha=seq(0,1,length=21),
                                        lambda=exp(seq(3,-5,length=100))),
                   trControl=ctrl1)

elastic.fit11$bestTune

myCol <- rainbow(25)
myPar <- list(superpose.symbol=list(col=myCol),
              superpose.line=list(col=myCol))
plot(elastic.fit11,par.settings=myPar)



coef(elastic.fit11$finalModel,s=elastic.fit11$bestTune$lambda)

lm.damage.par <- lm(log(damage) ~ season + nature + maxspeed + meanspeed + percent_usa + beta4, data= hurricane43.infor1)
summary(lm.damage.par)


```

## Elastic for death without parameter information
```{r}
set.seed(1)

elastic.fit20 <- train(log(deaths)~.,
                   data=hurricaneOutcome2,
                   method="glmnet",
                   tuneGrid=expand.grid(alpha=seq(0,1,length=21),
                                        lambda=exp(seq(7,-4,length=100))),
                   trControl=ctrl1)

elastic.fit20$bestTune

myCol <- rainbow(25)
myPar <- list(superpose.symbol=list(col=myCol),
              superpose.line=list(col=myCol))
plot(elastic.fit20,par.settings=myPar)



coef(elastic.fit20$finalModel,s=elastic.fit20$bestTune$lambda)

lm.death.nopar <- lm(log(deaths) ~ maxspeed + meanspeed + maxpressure +  percent_poor,hurricaneOutcome2)
summary(lm.death.nopar)


```

## Elastic for death with parameter information
```{r}
set.seed(2)
hurricane43.infor2 <- hurricane43.infor %>% select(-damage)
elastic.fit21 <- train(log(deaths)~.,
                   data=hurricane43.infor2,
                   method="glmnet",
                   preProcess = c("center","scale"),
                   tuneGrid=expand.grid(alpha=seq(0,1,length=21),
                                        lambda=exp(seq(3,-5,length=100))),
                   trControl=ctrl1)



elastic.fit21$bestTune

myCol <- rainbow(25)
myPar <- list(superpose.symbol=list(col=myCol),
              superpose.line=list(col=myCol))
plot(elastic.fit21,par.settings=myPar)

coef(elastic.fit21$finalModel,s=elastic.fit21$bestTune$lambda)

lm.death.par <- lm(log(deaths) ~ maxpressure + percent_poor ,hurricane43.infor2)
summary(lm.death.par)

```