---
title: "Conditional posterior distributions"
author: "Wen Cheng, Yimiao Pang"
date: "5/5/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## For $\sigma^{2}$

Let $\tau = 1/\sigma^{2}$, then

$$(\tau|\boldsymbol{\beta}, \textbf{B}, \Sigma^{-1}, Y) \propto \tau^{1+\frac{\sum_{i = 1}^{n}m_i}{2}} exp(-\tau \times \frac{1}{2}\sum_{i = 1}^{n}(Y_i - X_i\beta_i^{T})^{T}(Y_i - X_i\beta_i^{T} )$$
Thus, $\sigma^2$ is from inverse-gamma distribution

$$(\sigma^2 \mid \boldsymbol{\beta}, \textbf{B}, \Sigma^{-1}, Y) \sim \text{Inv-Gamma}(\frac{\sum_{i = 1}^{n}m_i}{2},  \frac{1}{2}\sum_{i = 1}^{n}(Y_i - X_i\beta_i^{T})(Y_i - X_i\beta_i^{T}).$$

## For \textbf{B}

\begin{align}
\pi (\textbf{B}| \boldsymbol{\beta}, \sigma^{2},\Sigma^{-1}, Y) 
& \propto exp(-\frac{1}{2}\sum_{i = 1}^{n} \left[ (Y_i - X_i\beta_i^{T})^{T}(\sigma^{2}I)^{-1}(Y_i - X_i\beta_i^{T})+(\beta_i - \beta)\Sigma^{-1}(\beta_1 - \beta)^{T} \right]) \\
& \propto exp(-\frac{1}{2}\sum_{i = 1}^{n} \left[ \beta_i(X_i^{T}(\sigma^{2}I)^{-1}X_i + \Sigma^{-1})\beta_i^{T} - 2\beta_i(X_i(\sigma^{2}I)^{-1})Y_i + \Sigma^{-1}\beta^{T} \right] )
\end{align}

Let $V_i = X_i^{T}(\sigma^{2}I)^{-1})X_i + \Sigma^{-1}$, and $U_i = X_i(\sigma^{2}I)^{-1}Y_i + \Sigma^{-1}\beta^{T}$, then

$$(\boldsymbol{\beta}_i \mid \boldsymbol{\beta}, \Sigma^{-1}, \sigma^2, Y) \sim \mathcal MVN(V_i^{-1}U_i, V_i^{-1}).$$

## For $\beta$

\begin{align}
\pi(\boldsymbol{\beta} | \textbf{B}, \sigma^{2},\Sigma^{-1}, Y) 
& \propto exp(-\frac{1}{2}\sum_{i = 1}^{n} (\beta_i - \beta)\Sigma^{-1}(\beta_i - \beta)^{T})\\
& \propto exp(-\frac{1}{2}\sum_{i = 1}^{n} \left[ \beta \Sigma^{-1}\beta^{T} - 2\beta \Sigma^{-1} \beta_i^{T} \right] )
\end{align}

Let $V = n \Sigma^{-1}, U = \sum_{i = 1}^{n} \Sigma^{-1} \beta_i^{T}$, then

$$ (\boldsymbol{\beta}| \textbf{B}, \sigma^{2},\Sigma^{-1}, Y) \sim \mathcal MVN(V^{-1}U, V^{-1}).$$


## For $\Sigma^{-1}$

\begin{align}
\pi(\Sigma^{-1}| \boldsymbol{\beta}, \textbf{B}, \sigma^{2}, Y) 
& \propto |\Sigma|^{-(d+1)}exp(-\frac{1}{2}tr(\Sigma^{-1})|\Sigma|^{-\frac{n}{2}} exp(-\frac{1}{2}\sum_{i = 1}^{n} (\beta_i - \beta)\Sigma^{-1}(\beta_i - \beta)^{T})\\
& \propto |\Sigma^{-1}|^{d+1+\frac{n}{2}}exp(-\frac{1}{2} \left[ tr(\Sigma^{-1}) + tr(\sum^n_{i=1}(\beta_i - \beta)\Sigma^{-1}(\beta_i - \beta)^{T}) \right] \\
& \propto |\Sigma^{-1}|^{3d+3+n-d-1} exp(-\frac{1}{2} tr( \left[ I + \sum_{i = 1}^{n}(\beta_i - \beta)^{T}(\beta_i - \beta) \right] \Sigma^{-1}))
\end{align}

Thus,
$$ \Sigma^{-1} \sim \mathcal W_d (\Psi, v),$$
where $v = 3d+3+n$, and $\Psi = I + \sum_{i = 1}^{n}(\beta_i - \beta)^{T}(\beta_i - \beta)$.